excluded:
  - "*/.build"

opt_in_rules:
  - array_init
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - comma_inheritance
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - direct_return
  - discarded_notification_center_observer
  - discouraged_assert
  - discouraged_object_literal
  - empty_collection_literal
  - empty_string
  - explicit_init
  - fallthrough
  - file_header
  - file_name_no_space
  - first_where
  - flatmap_over_map_reduce
  - ibinspectable_in_extension
  - identical_operands
  - joined_default_parameter
  - last_where
  - legacy_multiple
  - let_var_whitespace
  - local_doc_comment
  - lower_acl_than_parent
  - multiline_function_chains
  - multiline_parameters
  - multiline_parameters_brackets
  - nimble_operator
  - operator_usage_whitespace
  - optional_enum_case_matching
  - overridden_super_call
  - period_spacing
  - prefer_self_type_over_type_of_self
  - prefer_zero_over_explicit_init
  - private_outlet
  - prohibited_super_call
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - raw_value_for_camel_cased_codable_enum
  - reduce_into
  - redundant_nil_coalescing
  - required_enum_case
  - self_binding
  - shorthand_optional_binding
  - single_test_class
  - sorted_first_last
  - toggle_bool
  - unneeded_parentheses_in_closure_argument
  - untyped_error_in_catch
  - vertical_parameter_alignment_on_call
  - weak_delegate
  - xct_specific_matcher
  - yoda_condition

disabled_rules:
  - block_based_kvo
  - force_cast
  - force_try
  - opening_brace
  - trailing_comma
  - unneeded_override

trailing_whitespace:
  ignores_empty_lines: true
    
switch_case_alignment:
  indented_cases: true

function_parameter_count:
  warning: 6

nesting:
  type_level:
    warning: 2

vertical_whitespace:
  max_empty_lines: 2

file_length:
  warning: 2000

line_length:
  warning: 1000

type_body_length:
  warning: 1200

function_body_length:
  warning: 350

large_tuple:
  warning: 3

cyclomatic_complexity:
  ignores_case_statements: true
  warning: 15

identifier_name:
  max_length:
    warning: 60
  min_length:
    warning: 2
  excluded:
    - shiftJIS_X0213
    - x
    - y

type_name:
  allowed_symbols: "_"

custom_rules:
  inline_comment_spaces:
    name: "Spaces Before Inline Comment"
    regex: '\S ?//'
    match_kinds:
      - comment
    message: "There should be more than 2 spaces before an inline comment."
    severity: warning

  empty_first_line:
    name: "Empty First Line"
    regex: '(^[ a-zA-Z ]*(?:protocol|extension|class|struct) (?!(?:var|let))[ a-zA-Z:]*\{\n *\S+)'
    message: "There should be an empty line after a declaration"
    severity: warning
