deployment_target:
  macOS_deployment_target: 10.12.2

included:
  - CotEditor/Sources
  - Tests

opt_in_rules:
  - anyobject_protocol
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_first_not_nil
  - discouraged_optional_boolean
  - empty_string
  - empty_xctest_method
  - explicit_init
  - explicit_self
  - extension_access_modifier
  - fallthrough
  - file_header
  - first_where
  - identical_operands
  - implicit_return
  - joined_default_parameter
  - last_where
  - legacy_multiple
  - legacy_random
  - let_var_whitespace
  - lower_acl_than_parent
  - multiline_function_chains
  - multiline_parameters
  - multiline_parameters_brackets
  - nimble_operator
  - overridden_super_call
  - pattern_matching_keywords
  - private_outlet
  - prohibited_super_call
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - reduce_into
  - redundant_nil_coalescing
  - redundant_type_annotation
  - required_enum_case
  - single_test_class
  - sorted_first_last
  - static_operator
  - toggle_bool
  - untyped_error_in_catch
  - unused_import
  - unused_private_declaration
  - vertical_parameter_alignment_on_call
  - xct_specific_matcher
  - yoda_condition

disabled_rules:
  - block_based_kvo
  - force_cast
  - force_try
  - nesting
  - opening_brace
  - pattern_matching_keywords
  - trailing_comma
  - unused_closure_parameter
  - weak_delegate

private_outlet:
  allow_private_set: true
  
trailing_whitespace:
  ignores_empty_lines: true

attributes:
  always_on_same_line: ["@IBAction", "@objc"]

function_parameter_count:
  warning: 7

vertical_whitespace:
  max_empty_lines: 4

file_length:
  warning: 2000
  error: 3000

line_length:
  warning: 1000
  error: 2000

type_body_length:
  warning: 1000
  error: 1500

function_body_length:
  warning: 90
  error: 100

cyclomatic_complexity:
  warning: 30
  error: 50

large_tuple:
  warning: 3
  error: 6

identifier_name:
  max_length:
    warning: 60
    error: 100
  min_length:
    warning: 2
  excluded:
    - x
    - y
    - shiftJIS_X0213
    - version3_0


custom_rules:
  comment_space:
    name: "Space After Comment"
    regex: '//\S'
    match_kinds:
      - comment
    message: "There should be a space after a comment delimiter."
    severity: warning

  inline_comment_spaces:
    name: "Spaces Before Inline Comment"
    regex: '\S ?//'
    match_kinds:
      - comment
    message: "There should be more than 2 spaces before an inline comment."
    severity: warning

  empty_first_line:
    name: "Empty First Line"
    regex: '(^[ a-zA-Z ]*(?:protocol|extension|class|struct) (?!(?:var|let))[ a-zA-Z:]*\{\n *\S+)'
    message: "There should be an empty line after a declaration"
    severity: warning
