#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
cot

CotEditor
http://coteditor.com

Created by 1024jp on 2015-08-12.

------------------------------------------------------------------------------

© 2015 1024jp

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

"""

import re
import os.path
import sys
from subprocess import Popen, PIPE


# meta data
__version__ = '2.2.0'


# constants
APPLICATION_NAME = 'CotEditor'


def run_osascript(script):
    """Run osascript.

    script -- [str] Osascript.
    """
    p = Popen(['osascript', '-'], stdin=PIPE, stdout=PIPE)
    stdout, stderr = p.communicate(script)

    return stdout.rstrip()


def open_path(path, application):
    """Open given file path in desired application.

    path -- [str] Path to file.
    application -- [str] Name of application to open the file.
    """
    path = path.replace('"', '\\"')
    script = 'tell app "{}" to open POSIX file "{}"'.format(application, path)

    run_osascript(script)


def print_version():
    """Display version to the standard output.
    """
    print("cot {}".format(__version__))


if __name__ == "__main__":
    path = sys.argv[1]
    path = os.path.abspath(path)
    open_path(path, APPLICATION_NAME)
