attributes: []
characters:
- beginString: \
commands: []
commentDelimiters:
  inlineDelimiter: '#'
comments: []
completions: []
extensions: []
filenames:
- keyString: Dockerfile
interpreters: []
keywords:
- beginString: ADD
- beginString: ARG
- beginString: CMD
- beginString: COPY
- beginString: ENTRYPOINT
- beginString: ENV
- beginString: EXPOSE
- beginString: FROM
- beginString: HEALTHCHECK
- beginString: LABEL
- beginString: MAINTAINER
- beginString: ONBUILD
- beginString: RUN
- beginString: SHELL
- beginString: STOPSIGNAL
- beginString: USER
- beginString: VOLUME
- beginString: WORKDIR
kind: code
metadata:
  author: 1024jp
  distributionURL: https://coteditor.com
  lastModified: '2023-05-05'
  license: Same as CotEditor
  version: 1.1.0
numbers: []
outlineMenu: []
strings:
- beginString: '"'
  endString: '"'
- beginString: ''''
  endString: ''''
types: []
values: []
variables: []
