attributes: []
characters: []
commands:
- beginString: AR
- beginString: AS
- beginString: CC
- beginString: CO
- beginString: CPP
- beginString: CTANGLE
- beginString: CWEAVE
- beginString: CXX
- beginString: FC
- beginString: GET
- beginString: LEX
- beginString: MAKEINFO
- beginString: PC
- beginString: RM
- beginString: TANGLE
- beginString: TEX
- beginString: TEXI2VDI
- beginString: WEAVE
- beginString: YACC
- beginString: YACCR
commentDelimiters:
  inlineDelimiter: '#'
comments: []
completions: []
extensions: []
filenames:
- keyString: Makefile
- keyString: makefile
- keyString: GNUmakefile
interpreters:
- keyString: make
keywords:
- beginString: ^[^ ]+(?= *:[^=])
  regularExpression: true
- beginString: do
- beginString: done
- beginString: else
- beginString: endif
- beginString: export
- beginString: for
- beginString: ifdef
- beginString: ifeq
- beginString: ifndef
- beginString: ifneq
- beginString: include
- beginString: override
- beginString: unexport
- beginString: vpath
- beginString: while
kind: code
metadata:
  author: 1024jp
  distributionURL: https://coteditor.com
  lastModified: '2024-04-06'
  license: Same as CotEditor
  version: 1.4.0
numbers: []
outlineMenu: []
strings:
- beginString: '"'
  endString: '"'
types: []
values: []
variables:
- beginString: $%
- beginString: $(
  endString: )
- beginString: $*
- beginString: $+
- beginString: $<
- beginString: $?
- beginString: $@
- beginString: $^
- beginString: ${
  endString: '}'
- beginString: ^[-\w]+(?= +[?:+]?= )
  regularExpression: true
