extensions: []
filenames:
- keyString: "Makefile"
- keyString: "makefile"
completionsArray: []
outlineMenuArray: []
commandsArray:
- beginString: "AR"
- beginString: "AS"
- beginString: "CC"
- beginString: "CO"
- beginString: "CPP"
- beginString: "CTANGLE"
- beginString: "CWEAVE"
- beginString: "CXX"
- beginString: "FC"
- beginString: "GET"
- beginString: "LEX"
- beginString: "MAKEINFO"
- beginString: "PC"
- beginString: "RM"
- beginString: "TANGLE"
- beginString: "TEX"
- beginString: "TEXI2VDI"
- beginString: "WEAVE"
- beginString: "YACC"
- beginString: "YACCR"
metadata:
  author: "1024jp"
  distributionURL: "http://coteditor.github.io"
  version: "1.1"
  license: "Same as CotEditor"
  lastModified: "2014-09-24"
styleName: "Makefile"
charactersArray: []
commentsArray: []
valuesArray: []
variablesArray:
- beginString: "$%"
- beginString: "$("
  endString: ")"
- beginString: "$*"
- beginString: "$+"
- beginString: "$<"
- beginString: "$?"
- beginString: "$@"
- beginString: "$^"
- beginString: "${"
  endString: "}"
- beginString: "^[-\\w]+(?= +[?:+]?= )"
  regularExpression: true
numbersArray: []
stringsArray:
- beginString: "\""
  endString: "\""
keywordsArray:
- beginString: "^[^ ]+(?= *:[^=])"
  regularExpression: true
- beginString: "do"
- beginString: "done"
- beginString: "else"
- beginString: "endif"
- beginString: "export"
- beginString: "for"
- beginString: "ifdef"
- beginString: "ifeq"
- beginString: "ifndef"
- beginString: "ifneq"
- beginString: "include"
- beginString: "override"
- beginString: "unexport"
- beginString: "vpath"
- beginString: "while"
commentDelimiters:
  inlineDelimiter: "#"
