extensions: []
filenames:
- keyString: "Makefile"
- keyString: "makefile"
interpreters:
- keyString: "make"
completions: []
outlineMenu: []
commands:
- beginString: "AR"
- beginString: "AS"
- beginString: "CC"
- beginString: "CO"
- beginString: "CPP"
- beginString: "CTANGLE"
- beginString: "CWEAVE"
- beginString: "CXX"
- beginString: "FC"
- beginString: "GET"
- beginString: "LEX"
- beginString: "MAKEINFO"
- beginString: "PC"
- beginString: "RM"
- beginString: "TANGLE"
- beginString: "TEX"
- beginString: "TEXI2VDI"
- beginString: "WEAVE"
- beginString: "YACC"
- beginString: "YACCR"
metadata:
  author: "1024jp"
  distributionURL: "https://coteditor.com"
  version: "1.2"
  license: "Same as CotEditor"
  lastModified: "2015-08-13"
characters: []
comments: []
values: []
variables:
- beginString: "$%"
- beginString: "$("
  endString: ")"
- beginString: "$*"
- beginString: "$+"
- beginString: "$<"
- beginString: "$?"
- beginString: "$@"
- beginString: "$^"
- beginString: "${"
  endString: "}"
- beginString: "^[-\\w]+(?= +[?:+]?= )"
  regularExpression: true
numbers: []
strings:
- beginString: "\""
  endString: "\""
keywords:
- beginString: "^[^ ]+(?= *:[^=])"
  regularExpression: true
- beginString: "do"
- beginString: "done"
- beginString: "else"
- beginString: "endif"
- beginString: "export"
- beginString: "for"
- beginString: "ifdef"
- beginString: "ifeq"
- beginString: "ifndef"
- beginString: "ifneq"
- beginString: "include"
- beginString: "override"
- beginString: "unexport"
- beginString: "vpath"
- beginString: "while"
commentDelimiters:
  inlineDelimiter: "#"
